# Generated by Django 6.0.7 on 2026-07-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_TASK001_review_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, default='', max_length=300, verbose_name='行先')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='更新開始日時')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='戻り予定日時')),
                ('updated_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='employees.employee', verbose_name='社員')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='employees.statusmaster', verbose_name='状態')),
            ],
            options={
                'verbose_name': '現在状態',
                'verbose_name_plural': '現在状態一覧',
                'db_table': 'presence',
            },
        ),
        migrations.CreateModel(
            name='PresenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, default='', max_length=300, verbose_name='行先')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='更新開始日時')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='戻り予定日時')),
                ('updated_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新者ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_histories', to='employees.employee', verbose_name='社員')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_histories', to='employees.statusmaster', verbose_name='状態')),
            ],
            options={
                'verbose_name': '状態変更履歴',
                'verbose_name_plural': '状態変更履歴一覧',
                'db_table': 'presence_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
