# Generated by Django 6.0.7 on 2026-07-11 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_TASK001_review_fix'),
        ('presence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='presencehistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['updated_at'], name='idx_presence_updated_at'),
        ),
        migrations.AddIndex(
            model_name='presencehistory',
            index=models.Index(fields=['employee', 'created_at'], name='idx_p_hist_emp_created'),
        ),
        migrations.AddIndex(
            model_name='presencehistory',
            index=models.Index(fields=['employee', 'status'], name='idx_p_hist_emp_status'),
        ),
    ]
