# Generated by Django 6.0.7 on 2026-07-12 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_TASK001_review_fix'),
        ('presence', '0002_alter_presence_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255, verbose_name='行先名')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_destinations', to='employees.employee', verbose_name='社員')),
            ],
            options={
                'verbose_name': 'お気に入り行先',
                'verbose_name_plural': 'お気に入り行先一覧',
                'db_table': 'favorite_destination',
                'ordering': ['display_order', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'destination'), name='unique_favorite_destination')],
            },
        ),
    ]
