# Generated by Django 6.0.7 on 2026-07-12 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_TASK001_review_fix'),
        ('presence', '0003_favoritedestination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('target_date', models.DateField(verbose_name='対象日')),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='行先')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='メモ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_statuses', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_statuses', to='employees.employee', verbose_name='社員')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_statuses', to='employees.statusmaster', verbose_name='状態')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scheduled_statuses', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '事前登録予定',
                'verbose_name_plural': '事前登録予定一覧',
                'db_table': 'scheduled_status',
                'ordering': ['target_date', 'start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'target_date'), name='unique_scheduled_status')],
            },
        ),
    ]
