# Generated by Django 6.0.7 on 2026-07-12 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_TASK001_review_fix'),
        ('presence', '0004_scheduledstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'ログイン成功'), ('LOGIN_FAILED', 'ログイン失敗'), ('LOGOUT', 'ログアウト'), ('PRESENCE_UPDATE', '状態変更'), ('ADMIN_OP', '管理操作')], max_length=50, verbose_name='操作種別')),
                ('description', models.TextField(verbose_name='詳細内容')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='IPアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='employees.employee', verbose_name='対象社員')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ一覧',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='idx_audit_log_action_created'), models.Index(fields=['employee', 'created_at'], name='idx_audit_log_emp_created'), models.Index(fields=['created_at'], name='idx_audit_log_created_at')],
            },
        ),
    ]
