# Generated by Django 6.0.7 on 2026-07-12 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_TASK001_review_fix'),
        ('presence', '0005_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='presencehistory',
            index=models.Index(fields=['created_at'], name='idx_p_hist_created_at'),
        ),
        migrations.AddIndex(
            model_name='presencehistory',
            index=models.Index(fields=['status'], name='idx_p_hist_status_id'),
        ),
    ]
