# Generated by Django 6.0.7 on 2026-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0006_presencehistory_idx_p_hist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledstatus',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='適用日時'),
        ),
    ]
