"""
Django settings for Presence Board project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env ファイルの読み込み
load_dotenv(BASE_DIR / '.env')


# ==============================================================================
# セキュリティ設定
# ==============================================================================

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-key-do-not-use-in-production')

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')


# ==============================================================================
# アプリケーション定義
# ==============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # サードパーティ
    'rest_framework',
    'drf_spectacular',
    # プロジェクトアプリ（追加予定）
    # 'apps.presence',
    # 'apps.employees',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==============================================================================
# データベース設定 (PostgreSQL)
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'presence_board'),
        'USER': os.environ.get('POSTGRES_USER', 'presence_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'presence_password'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# ==============================================================================
# パスワードバリデーション
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# 国際化
# ==============================================================================

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# 静的ファイル
# ==============================================================================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']


# ==============================================================================
# Django REST Framework 設定
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',  # AI エージェント向け
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    # エラーレスポンスは 06_API設計.md のフォーマットに準拠
    # error_code / message / details
}


# ==============================================================================
# OpenAPI (drf-spectacular) 設定
# ==============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'Presence Board API',
    'DESCRIPTION': '社内行先在席管理システム (Internal Presence Management System) REST API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# ==============================================================================
# システム設定 (02_要件定義.md / 05_DB設計.md 参照)
# ==============================================================================

PRESENCE_HISTORY_RETENTION_DAYS = 30
SSE_HEARTBEAT_INTERVAL = 30
SESSION_TIMEOUT_MINUTES = 480
FAVORITE_DESTINATION_MAX = 10
RECENT_DESTINATION_MAX = 20


# ==============================================================================
# その他
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
