# Generated by Django 6.0.7 on 2026-07-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='課名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
            ],
            options={
                'verbose_name': '課',
                'verbose_name_plural': '課一覧',
                'db_table': 'department',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PRESENT', '在席'), ('CUSTOMER', '客先・客先常駐'), ('OUT', '外出・出張'), ('MEETING', '会議'), ('REMOTE', '在宅勤務・リモート'), ('HOLIDAY', '休暇'), ('LEAVE', '退社'), ('DIRECT_HOME', '直帰')], max_length=50, unique=True, verbose_name='状態コード')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '状態マスタ',
                'verbose_name_plural': '状態マスタ一覧',
                'db_table': 'status_master',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='会社名')),
                ('office_name', models.CharField(max_length=200, verbose_name='事業所名')),
                ('address', models.CharField(max_length=500, verbose_name='住所')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
            ],
            options={
                'verbose_name': '勤務場所',
                'verbose_name_plural': '勤務場所一覧',
                'db_table': 'work_location',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='グループ名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='employees.department', verbose_name='課')),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ一覧',
                'db_table': 'group',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=10, unique=True, verbose_name='社員番号')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, verbose_name='連絡先')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department', verbose_name='課')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.group', verbose_name='グループ')),
                ('work_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.worklocation', verbose_name='勤務場所')),
            ],
            options={
                'verbose_name': '社員',
                'verbose_name_plural': '社員一覧',
                'db_table': 'employee',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['employee_no'], name='idx_employee_no'), models.Index(fields=['email'], name='idx_employee_email'), models.Index(fields=['group_id'], name='idx_employee_group'), models.Index(fields=['department_id'], name='idx_employee_department'), models.Index(fields=['display_order'], name='idx_employee_display_order')],
            },
        ),
    ]
