# Generated by Django 6.0.7 on 2026-07-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_TASK001_create_employee_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='idx_employee_no',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='idx_employee_email',
        ),
        migrations.AlterField(
            model_name='department',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='課名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='group',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='statusmaster',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='worklocation',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='uq_group_department_name'),
        ),
    ]
